---
title: "Using ensembler with Domino Datalab"
author: "Benjamin Paul Rollert"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

Domino Datalab (www.dominoup.com) offers a powerful platform for training models in the cloud. The `ensembler` package aims to make it easier to launch, train, and combine models by extending the functionality of both the `domino` and `caret` packages. In this vingette, we'll cover a simple use case in which we train a classifier on the classic `BreastCancer` dataset. 

## Logging into Domino

Assuming you already have a Domino account, the first step is to log into Domino from R:
```
install.packages("domino")
library(domino)
domino.login("username", "password")
```

## Create a domino project
We need to create a domino project:

```
domino.create("my-new-project")
# current working directory is now switched to ./my-new-project and new project is initialized.
```

From here on out, we will work out of the directory our Domino project is in.



## Load the data

The next step is to split our data into training and test sets, and then save the results in an .Rda file. For this example, we attach the BreastCancer dataset from the `mlbench` packge. The `mlbench` package contains useful datasets for benchmarking machine learning algorithms. Note that we also impute missing values using `rfImpute` from the `randomForest` package for conevenience - but it's normally not a kosher practice to impute values on the test set using the test set labels!

```
library(mlbench)
library(caret)
library(randomForest)
data(BreastCancer)

BreastCancer <- BreastCancer[ ,-1]
BreastCancer <- rfImpute(data=BreastCancer, y=BreastCancer$Class, x=BreastCancer[ ,1:9])
colnames(BreastCancer)[1] <- c("Class")

inTrain <- createDataPartition(y= BreastCancer$Class, p=.8, list=FALSE)
training <- BreastCancer[inTrain, ]
testing <- BreastCancer[-inTrain, ]


save(training, testing, file="BreastCancer.Rda")
```
We name our .Rda file "BreastCancer.Rda". We could use a more sophisticated naming convention for the dataset, or any name we want for that matter. The important thing is to remember the name as we will need to reference the name of the .Rda file in the future.
Our datasets will be pushed to Domino's remote server as soon as we launch a run. 

## Create a script to train caret methods.
This is the trickiest part, as it requires us to build a script that can generalize well across many different methods. For this demo, our script is flexible enough to accomodate virtually any binary classification method in the `caret` package.

Below is a sample script for our demo, that we title `variable_model.R`:

```
install.packages("mboost")
library(caret)
library(doParallel)
registerDoParallel(detectCores())



dataset <- commandArgs(trailingOnly = TRUE)[1]
load(paste0(dataset,".Rda"))

formula <- as.formula(commandArgs(trailingOnly = TRUE)[2])

method <- commandArgs(trailingOnly = TRUE)[3]

n_samples <- 10
set.seed(12)
folds <- createFolds(training$Class, n_samples, returnTrain = TRUE)


trCtrl <- trainControl(method = "cv", 
                       number = n_samples, 
                       summaryFunction=twoClassSummary,
                       allowParallel = TRUE,
                       classProbs =  TRUE,
                       savePredictions=TRUE,
                       index = folds)

model <- train(formula, 
               data = training,
               metric="ROC",
               method = method,
               trControl = trCtrl)

print(model)

results <- model$results
results <- results[which.max(results$ROC), c("ROC",    "Sens",   "Spec",   "ROCSD",  "SensSD",  "SpecSD")]
results <- cbind(results, data.frame(model = rep(method, nrow(results))))

save(results, file = sprintf("results_%s_%s.Rda", dataset, method))#save best results vector
save(model, file = sprintf("model_obj_%s_%s.Rda", dataset, method))#save object of class "train"
```
After having saved the above script as `variable_model.R` in our working directory, we are ready to launch some runs.

##Launch runs to train multiple caret methods on the same dataset, in parallel
We now decide on a set of caret methods we wish to train on our training data. We also decide on the formula to pass to caret train; in this case we want to train on all features in the training data. Then we launch runs on domino by programmatically passing our caret methods as arguments to the script `variable_model.R`

```
library(ensembler)
library(domino)
dataset <- "BreastCancer"

#vector specifying different caret methods
models_breast <- c("nnet", "rf", "svmLinear", "svmRadial", "svmPoly", "gbm", "glm", "glmboost")

launcher(script = "variable_model.R", dataset=dataset, par=models_breast, formula = "Class~.")
```
Notice that we pass the name of the dataset as a variable. This is so that we load the appropriate .Rda file with dataset we wish to train on.

##Downloading and combining results from Domino runs
Now we're going to download the .Rda files from Domino and combine the results.

```
library(caret)
library(ensembler)
library(domino)
domino.download()#downloads .Rda files into our working directory

dataset <- "BreastCancer"
label <- "malignant"
load(paste0(dataset, ".Rda"))#load training and test data

#compare accuracy of models
models_breast <- c("nnet", "rf", "svmLinear", "svmRadial", "svmPoly", "gbm", "glm", "glmboost") #name of methods we launched in previous step
ordered_acc <- compare(models_breast, dataset=dataset, metric="ROC")
print(ordered_acc)
#ROC      Sens      Spec       ROCSD     SensSD     SpecSD     model
#8  0.9931318 0.9753754 0.9328947 0.008100897 0.01569929 0.06532880  glmboost
#5  0.9921756 0.9372372 0.9897368 0.009119749 0.02283511 0.02164553   svmPoly
#21 0.9911288 0.9725976 0.9586842 0.010071101 0.02248147 0.04058001        rf
#31 0.9904566 0.9617117 0.9844737 0.010518603 0.02949558 0.03522888 svmRadial
#6  0.9903658 0.9753754 0.9431579 0.012583448 0.02021861 0.04558366       gbm
#2  0.9897025 0.9725976 0.9428947 0.013921302 0.02248147 0.03005714      nnet
#3  0.9828287 0.9644895 0.9226316 0.019389698 0.02586685 0.07367586 svmLinear
#7  0.9549361 0.9617868 0.8544737 0.026650048 0.02629045 0.05517328       glm
print(ordered_acc[which.max(ordered_acc$ROC), ])#model with greatest ROC
#ROC      Sens      Spec       ROCSD     SensSD    SpecSD    model
#8 0.9931318 0.9753754 0.9328947 0.008100897 0.01569929 0.0653288 glmboost
```
We've loaded the results from the caret train objects on our local machine, and combined them in one data.frame so that we can directly compare the accuracy of different models.
As mentioned in the previous step, we need to specify the name of the dataset, as this allows us to load the correct .Rda files; the name passed to `compare` must be identical to the name we used in the `launcher` function.

##build a caretList from our caret train models
We're finally ready to build an ensemble from the models we trained on Domino. `ensembler` can create objects of class `caretList` in order to integrate with the 
`caretEnsemble` package.

```
model_list <- load_caret_list(dataset="BreastCancer", models=models)
greedy_ensemble <- caretEnsemble(model_list)#greedy forward selection
#$weights
#nnet   rf 
#0.64 0.36 

#use optimal blend as an ensemble, predict on test data
ens_preds <- predict(greedy_ensemble, newdata=testing)


#reference vector
reference <- ifelse(testing$Class == label, 1, 0)
aucFun(ens_preds, reference)
#0.985348
```

Once we have created a `caretList` object we can use any of the methods from the `caretEnsemble` package, including `caretStack`. To learn more about the `caretEnsemble` package,
check out the [caretEnsemble vignette](http://cran.r-project.org/web/packages/caretEnsemble/vignettes/caretEnsemble-intro.html)

##publish a live API endpoint
We can publish a live API endpoint on Domnino by creatining a script with the function we wish to invoke. In this case, we return a closure `APIFunc` containing the ensemble method we developed in the preceding step. We will name our script `Cancer_API.R`:

```
install.packages("mboost")
devtools::install_github("BenRollert/ensembler")
library(ensembler)

blender_fact <-  function(ensemble){
  function(Cl.thickness, Cell.size, Cell.shape, Marg.adhesion, Epith.c.size, Bare.nuclei, Bl.cromatin, Normal.nucleoli, Mitoses){
  df <- data.frame(Cl.thickness = Cl.thickness, Cell.size = Cell.size, Cell.shape = Cell.shape, Marg.adhesion = Marg.adhesion, Epith.c.size = Epith.c.size, Bare.nuclei = Bar.nuclei, Bl.cromatin = Bl.cromatin, Normal.nucleoli = Normal.nucleoli, Mitoses = Mitoses)
  df <- data.frame(lapply(df, as.factor))
  df[2, ] <- df[1, ]#hideous hack for bug on single row df in predict.caretEnsemble
  ens_preds <- predict(ensemble, newdata=df)
  ens_preds[1]
  }
}

model_list <- load_caret_list(dataset="BreastCancer", models=c("nnet", "rf", "svmLinear", "svmRadial", "svmPoly", "gbm", "glm", "glmboost"))
greedy_ensemble <- caretEnsemble::caretEnsemble(model_list)

APIFunc <- blender_fact(ensemble=greedy_ensemble)
```

In Domino, we publish the endpoint by speciying the script name `Cancer_API.R` and the function to invoke `APIFunc`. 

We can test the API endpoint with the following curl request passing inputs to our ensemble:

```
curl -v -X POST \
    https://endpoint.dominodatalab.com/v1/<username>/my-new-project/endpoint \
    -H "Content-Type: application/json" \
    -H 'X-Domino-Api-Key: <API Key>' \
    -d '{"parameters": [2, 3, 4, 2, 5, 3, 4, 2, 3]}'
    
```  



